sudo: false

language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  fast_finish: true

install:
  - composer self-update

before_script:
  - composer install --no-interaction

script:
  - ./vendor/bin/phpunit --coverage-clover=coverage.clover

after_script:
  - if [[ "$TRAVIS_PHP_VERSION" == "5.6" ]]; then php ./vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover; fi;
